export const environment = {
  production: false,
  envName: 'staging',
  api_base_url_v1: '',
  api_base_url_v2: '',
  api_base_url_v3: '',
  google_maps_api_key: '',
  azure_maps_api_key: '',
  azure_maps_api_base_url: 'https://atlas.microsoft.com',
  login_request_scopes: [],
  protected_resources_scopes: [],
  ad_b2c_signIn_signUp: '',
  ad_b2c_signUp: '',
  ad_b2c_reset_password: '',
  ad_b2c_signIn_signUp_authority: '',
  ad_b2c_signUp_authority: '',
  ad_b2c_reset_password_authority: '',
  ad_b2c_signIn_signUp_authority_domain: '',
  ad_b2c_client_id: '',
  ad_b2c_redirect_url: '',
  stripe_public_key: '',
  x_application_client_id: null,
  signalr_url: '',
};
