export * from './currencies.service';
import { CurrenciesService } from './currencies.service';
export * from './roamingInvoices.service';
import { RoamingInvoicesService } from './roamingInvoices.service';
export * from './roamingPoints.service';
import { RoamingPointsService } from './roamingPoints.service';
export * from './roamingSessions.service';
import { RoamingSessionsService } from './roamingSessions.service';
export * from './roamingTariffs.service';
import { RoamingTariffsService } from './roamingTariffs.service';
export * from './roamingTransactions.service';
import { RoamingTransactionsService } from './roamingTransactions.service';
export * from './roamingUsers.service';
import { RoamingUsersService } from './roamingUsers.service';
export const APIS = [CurrenciesService, RoamingInvoicesService, RoamingPointsService, RoamingSessionsService, RoamingTariffsService, RoamingTransactionsService, RoamingUsersService];
