export * from './campaigns.service';
import { CampaignsService } from './campaigns.service';
export * from './cards.service';
import { CardsService } from './cards.service';
export * from './chargePointInterestReviews.service';
import { ChargePointInterestReviewsService } from './chargePointInterestReviews.service';
export * from './chargePointInterestSessions.service';
import { ChargePointInterestSessionsService } from './chargePointInterestSessions.service';
export * from './chargePointInterestUserFavorites.service';
import { ChargePointInterestUserFavoritesService } from './chargePointInterestUserFavorites.service';
export * from './chargePointInterests.service';
import { ChargePointInterestsService } from './chargePointInterests.service';
export * from './chargePoints.service';
import { ChargePointsService } from './chargePoints.service';
export * from './chargeSessions.service';
import { ChargeSessionsService } from './chargeSessions.service';
export * from './cities.service';
import { CitiesService } from './cities.service';
export * from './connectors.service';
import { ConnectorsService } from './connectors.service';
export * from './countries.service';
import { CountriesService } from './countries.service';
export * from './coupons.service';
import { CouponsService } from './coupons.service';
export * from './creditCards.service';
import { CreditCardsService } from './creditCards.service';
export * from './currencies.service';
import { CurrenciesService } from './currencies.service';
export * from './devUtils.service';
import { DevUtilsService } from './devUtils.service';
export * from './deviceTokens.service';
import { DeviceTokensService } from './deviceTokens.service';
export * from './directories.service';
import { DirectoriesService } from './directories.service';
export * from './directoryIntegrations.service';
import { DirectoryIntegrationsService } from './directoryIntegrations.service';
export * from './districts.service';
import { DistrictsService } from './districts.service';
export * from './integrations.service';
import { IntegrationsService } from './integrations.service';
export * from './invitations.service';
import { InvitationsService } from './invitations.service';
export * from './invoiceRequests.service';
import { InvoiceRequestsService } from './invoiceRequests.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './memberBillingInfos.service';
import { MemberBillingInfosService } from './memberBillingInfos.service';
export * from './nomuPayCallback.service';
import { NomuPayCallbackService } from './nomuPayCallback.service';
export * from './paymentGateway.service';
import { PaymentGatewayService } from './paymentGateway.service';
export * from './policies.service';
import { PoliciesService } from './policies.service';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './reservations.service';
import { ReservationsService } from './reservations.service';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './siteHosts.service';
import { SiteHostsService } from './siteHosts.service';
export * from './subscriptionPayments.service';
import { SubscriptionPaymentsService } from './subscriptionPayments.service';
export * from './subscriptions.service';
import { SubscriptionsService } from './subscriptions.service';
export * from './tariffs.service';
import { TariffsService } from './tariffs.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export * from './userFavoritedChargePoints.service';
import { UserFavoritedChargePointsService } from './userFavoritedChargePoints.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './vehicles.service';
import { VehiclesService } from './vehicles.service';
export * from './workspaces.service';
import { WorkspacesService } from './workspaces.service';
export const APIS = [CampaignsService, CardsService, ChargePointInterestReviewsService, ChargePointInterestSessionsService, ChargePointInterestUserFavoritesService, ChargePointInterestsService, ChargePointsService, ChargeSessionsService, CitiesService, ConnectorsService, CountriesService, CouponsService, CreditCardsService, CurrenciesService, DevUtilsService, DeviceTokensService, DirectoriesService, DirectoryIntegrationsService, DistrictsService, IntegrationsService, InvitationsService, InvoiceRequestsService, InvoicesService, MemberBillingInfosService, NomuPayCallbackService, PaymentGatewayService, PoliciesService, ReportsService, ReservationsService, ReviewsService, RolesService, SiteHostsService, SubscriptionPaymentsService, SubscriptionsService, TariffsService, TransactionsService, UserFavoritedChargePointsService, UsersService, VehiclesService, WorkspacesService];
