/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignVisibility } from './campaignVisibility';
import { Coupon } from './coupon';
import { CampaignStatus } from './campaignStatus';
import { ChargePointAccessibility } from './chargePointAccessibility';
import { CampaignOption } from './campaignOption';
import { CouponLimitType } from './couponLimitType';
import { WorkspaceCampaign } from './workspaceCampaign';
import { CampaignType } from './campaignType';


export interface Campaign { 
    readonly id?: string | null;
    created?: string;
    createdBy?: string | null;
    lastModified?: string | null;
    lastModifiedBy?: string | null;
    name?: string | null;
    slug?: string | null;
    subTitle?: string | null;
    description?: string | null;
    imageUrl?: string | null;
    campaignUrl?: string | null;
    status?: CampaignStatus;
    startDate?: string | null;
    endDate?: string | null;
    readonly readableId?: string | null;
    isArchived?: boolean;
    archiveDate?: string | null;
    archivedBy?: string | null;
    userId?: string | null;
    visibility?: CampaignVisibility;
    chargePointAccessibility?: ChargePointAccessibility;
    campaignType?: CampaignType;
    campaignAmount?: number | null;
    minimumEligibleAmount?: number | null;
    externalId?: string | null;
    campaignOptionId?: string | null;
    couponLimitType?: CouponLimitType;
    couponsCount?: number | null;
    campaignOption?: CampaignOption;
    coupons?: Array<Coupon> | null;
    applicationClientId?: string | null;
    photoUrls?: Array<string> | null;
    eligibleWorkspaces?: Array<WorkspaceCampaign> | null;
}
export namespace Campaign {
}


