/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChargeSessionStatus } from './chargeSessionStatus';
import { Connector } from './connector';
import { Coupon } from './coupon';
import { DomainEvent } from './domainEvent';
import { MemberBillingInfo } from './memberBillingInfo';
import { ChargePoint } from './chargePoint';
import { Tariff } from './tariff';
import { Review } from './review';
import { CreditCard } from './creditCard';
import { Card } from './card';
import { Transaction } from './transaction';
import { ChargeSessionData } from './chargeSessionData';
import { Directory } from './directory';
import { Workspace } from './workspace';


export interface ChargeSession { 
    readonly id?: string | null;
    created?: string;
    createdBy?: string | null;
    lastModified?: string | null;
    lastModifiedBy?: string | null;
    userId?: string | null;
    chargePointId?: string | null;
    connectorId?: string | null;
    connectorNumber?: number;
    workspaceId?: string | null;
    directoryId?: string | null;
    plateNo?: string | null;
    status?: ChargeSessionStatus;
    startDate?: string;
    endDate?: string;
    ocppTransactionId?: string | null;
    no?: number;
    readonly readableId?: string | null;
    startCardId?: string | null;
    stopCardId?: string | null;
    transactionId?: string | null;
    tariffId?: string | null;
    archivedBy?: string | null;
    startReason?: string | null;
    stopReason?: string | null;
    creditCardId?: string | null;
    creditCard?: CreditCard;
    startCard?: Card;
    stopCard?: Card;
    tariff?: Tariff;
    chargeSessionData?: ChargeSessionData;
    chargePoint?: ChargePoint;
    workspace?: Workspace;
    directory?: Directory;
    connector?: Connector;
    transaction?: Transaction;
    readonly domainEvents?: Array<DomainEvent> | null;
    isArchived?: boolean;
    archiveDate?: string | null;
    applicationClientId?: string | null;
    memberBillingInfo?: MemberBillingInfo;
    memberBillingInfoId?: string | null;
    coupon?: Coupon;
    couponId?: string | null;
    reviewId?: string | null;
    review?: Review;
}
export namespace ChargeSession {
}


