/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ChargePointSourceType = 'Undefined' | 'Simulator' | 'Basic' | 'Smart' | 'Standard' | 'Unknown';

export const ChargePointSourceType = {
    Undefined: 'Undefined' as ChargePointSourceType,
    Simulator: 'Simulator' as ChargePointSourceType,
    Basic: 'Basic' as ChargePointSourceType,
    Smart: 'Smart' as ChargePointSourceType,
    Standard: 'Standard' as ChargePointSourceType,
    Unknown: 'Unknown' as ChargePointSourceType
};

