/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignDto } from './campaignDto';
import { CouponCreationType } from './couponCreationType';
import { CouponCodeStatus } from './couponCodeStatus';


export interface CouponDto { 
    id?: string | null;
    expirationDate?: string | null;
    userId?: string | null;
    readableId?: string | null;
    campaignId?: string | null;
    campaign?: CampaignDto;
    externalId?: string | null;
    code?: string | null;
    status?: CouponCodeStatus;
    createdBy?: string | null;
    isArchived?: boolean;
    archiveDate?: string | null;
    archivedBy?: string | null;
    couponCreationType?: CouponCreationType;
    lastModified?: string | null;
}
export namespace CouponDto {
}


