/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateChargePointDto } from './createChargePointDto';


export interface CreateChargePointsCommand { 
    userId?: string | null;
    workspaceId?: string | null;
    chargePoints?: Array<CreateChargePointDto> | null;
}

