/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HolderPlatform } from './holderPlatform';


export interface CreateGenericCreditCardForDirectoryCommand { 
    cardAlias?: string | null;
    cardHoldername?: string | null;
    cardNumber?: string | null;
    expireMonth?: string | null;
    expireYear?: string | null;
    holderPlatform?: HolderPlatform;
    isPrimary?: boolean;
}
export namespace CreateGenericCreditCardForDirectoryCommand {
}


