/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CouponCreationType } from './couponCreationType';
import { CouponCodeStatus } from './couponCodeStatus';


export interface CreateCouponCommand { 
    campaignId?: string | null;
    userId?: string | null;
    code?: string | null;
    status?: CouponCodeStatus;
    expirationDate?: string | null;
    externalId?: string | null;
    couponCreationType?: CouponCreationType;
}
export namespace CreateCouponCommand {
}


