/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DirectionRouteLegDto } from './directionRouteLegDto';
import { ChargePointInterestSimpleDto } from './chargePointInterestSimpleDto';
import { Location } from './location';


export interface DirectionRouteDto { 
    polylineLocations?: Array<Location> | null;
    polyline?: string | null;
    totalDurationInSeconds?: number;
    totalDistanceInMeters?: number;
    legs?: Array<DirectionRouteLegDto> | null;
    chargePointsOnRoad?: Array<ChargePointInterestSimpleDto> | null;
}

