/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DirectionRouteDto } from './directionRouteDto';
import { Location } from './location';


export interface DirectionDto { 
    origin?: Location;
    destination?: Location;
    waypoints?: Array<Location> | null;
    summary?: string | null;
    extra?: string | null;
    readonly routes?: Array<DirectionRouteDto> | null;
}

