/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Integration } from './integration';
import { Directory } from './directory';


export interface DirectoryIntegration { 
    readonly id?: string | null;
    created?: string;
    createdBy?: string | null;
    lastModified?: string | null;
    lastModifiedBy?: string | null;
    directoryId?: string | null;
    directory?: Directory;
    integrationId?: string | null;
    integration?: Integration;
    isPrimary?: boolean;
}

