/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntegrationCategory } from './integrationCategory';


export interface IntegrationDto { 
    id?: string | null;
    name?: string | null;
    description?: string | null;
    logoUrl?: string | null;
    integrationCategory?: IntegrationCategory;
    slug?: string | null;
    parametersTemplate?: string | null;
}
export namespace IntegrationDto {
}


