/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InvitationStatus = 'Pending' | 'Accepted' | 'Completed' | 'Expired' | 'Failed' | 'Cancelled' | 'Rejected';

export const InvitationStatus = {
    Pending: 'Pending' as InvitationStatus,
    Accepted: 'Accepted' as InvitationStatus,
    Completed: 'Completed' as InvitationStatus,
    Expired: 'Expired' as InvitationStatus,
    Failed: 'Failed' as InvitationStatus,
    Cancelled: 'Cancelled' as InvitationStatus,
    Rejected: 'Rejected' as InvitationStatus
};

