/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type InvoiceRequestStatus = 'Created' | 'InvoiceRequested' | 'UploadedInvoice' | 'Complete' | 'Archived';

export const InvoiceRequestStatus = {
    Created: 'Created' as InvoiceRequestStatus,
    InvoiceRequested: 'InvoiceRequested' as InvoiceRequestStatus,
    UploadedInvoice: 'UploadedInvoice' as InvoiceRequestStatus,
    Complete: 'Complete' as InvoiceRequestStatus,
    Archived: 'Archived' as InvoiceRequestStatus
};

