/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TripPlannerSearchParams } from './tripPlannerSearchParams';
import { Location } from './location';
import { PlannedTripWayPoint } from './plannedTripWayPoint';


export interface PlannedTrip { 
    polyline?: string | null;
    origin?: Location;
    destination?: Location;
    chargePointsCountOnRoute?: number;
    plannedTripWayPoints?: Array<PlannedTripWayPoint> | null;
    tripPlannerSearchParams?: TripPlannerSearchParams;
    totalSolutionCost?: number;
    totalDistanceInMeters?: number;
    totalDurationInMinutes?: number;
}

