/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReservationStatus = 'Undefined' | 'Accepted' | 'Charging' | 'Cancelled' | 'CancelledWithPenalty';

export const ReservationStatus = {
    Undefined: 'Undefined' as ReservationStatus,
    Accepted: 'Accepted' as ReservationStatus,
    Charging: 'Charging' as ReservationStatus,
    Cancelled: 'Cancelled' as ReservationStatus,
    CancelledWithPenalty: 'CancelledWithPenalty' as ReservationStatus
};

