/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewStatus } from './reviewStatus';
import { ChargePointSimpleDto } from './chargePointSimpleDto';


export interface ReviewDto { 
    id?: string | null;
    rating?: number;
    username?: string | null;
    comment?: string | null;
    photoUrls?: Array<string> | null;
    created?: string;
    chargePointId?: string | null;
    chargePoint?: ChargePointSimpleDto;
    userId?: string | null;
    status?: ReviewStatus;
    isArchived?: boolean | null;
}
export namespace ReviewDto {
}


