/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReviewStatus = 'Undefined' | 'Rejected' | 'Pending' | 'WaitingForApproval' | 'Confirmed';

export const ReviewStatus = {
    Undefined: 'Undefined' as ReviewStatus,
    Rejected: 'Rejected' as ReviewStatus,
    Pending: 'Pending' as ReviewStatus,
    WaitingForApproval: 'WaitingForApproval' as ReviewStatus,
    Confirmed: 'Confirmed' as ReviewStatus
};

