/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RoamingPointReviewStatus = 'Rejected' | 'Undefined' | 'Pending' | 'WaitingForApproval' | 'InProgress' | 'Approved';

export const RoamingPointReviewStatus = {
    Rejected: 'Rejected' as RoamingPointReviewStatus,
    Undefined: 'Undefined' as RoamingPointReviewStatus,
    Pending: 'Pending' as RoamingPointReviewStatus,
    WaitingForApproval: 'WaitingForApproval' as RoamingPointReviewStatus,
    InProgress: 'InProgress' as RoamingPointReviewStatus,
    Approved: 'Approved' as RoamingPointReviewStatus
};

