/**
 * AdminApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceProfileId } from './invoiceProfileId';
import { InvoiceStatus } from './invoiceStatus';


export interface RoamingInvoiceDto { 
    id: string | null;
    supplierTaxNo: string | null;
    supplierName: string | null;
    customerTaxNo: string | null;
    customerName: string | null;
    statusMessage?: string | null;
    status?: InvoiceStatus;
    profileId?: InvoiceProfileId;
    issueDate?: string;
    lastUpdate?: string | null;
    transactionId: string | null;
    userId: string | null;
}
export namespace RoamingInvoiceDto {
}


