/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoamingPointReviewStatus } from './roamingPointReviewStatus';
import { RoamingPointSimpleDto } from './roamingPointSimpleDto';


export interface RoamingReviewDto { 
    id?: string | null;
    rating?: number | null;
    username?: string | null;
    comment?: string | null;
    photoUrls?: Array<string> | null;
    created?: string;
    chargePointInterestId?: string | null;
    chargePointInterest?: RoamingPointSimpleDto;
    userId?: string | null;
    status?: RoamingPointReviewStatus;
    isArchived?: boolean | null;
}
export namespace RoamingReviewDto {
}


