/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChargePoint } from './chargePoint';
import { LeaseSharingInfo } from './leaseSharingInfo';
import { Workspace } from './workspace';


export interface SiteHost { 
    readonly id?: string | null;
    created?: string;
    createdBy?: string | null;
    lastModified?: string | null;
    lastModifiedBy?: string | null;
    readonly readableId?: string | null;
    workspaceId?: string | null;
    workspace?: Workspace;
    name?: string | null;
    leaseSharingInfo?: LeaseSharingInfo;
    chargePoints?: Array<ChargePoint> | null;
    isArchived?: boolean;
    archiveDate?: string | null;
    archivedBy?: string | null;
}

