/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TariffType } from './tariffType';
import { TariffIdleFee } from './tariffIdleFee';
import { TariffStartingFee } from './tariffStartingFee';
import { BasePriceType } from './basePriceType';
import { TariffMinuteFee } from './tariffMinuteFee';
import { TariffChargingFee } from './tariffChargingFee';
import { CurrencyDto } from './currencyDto';


export interface TariffSimpleDto { 
    id?: string | null;
    name?: string | null;
    basePrice?: number;
    basePriceType?: BasePriceType;
    tariffType?: TariffType;
    isPrimary?: boolean;
    startingFee?: TariffStartingFee;
    chargingFee?: TariffChargingFee;
    minuteFee?: TariffMinuteFee;
    idleFee?: TariffIdleFee;
    currency?: CurrencyDto;
    connectedConnectorsCount?: number | null;
}
export namespace TariffSimpleDto {
}


