/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChargingPowerType } from './chargingPowerType';


export interface TripPlannerSearchParams { 
    minStops?: number;
    maxStops?: number;
    chargingTimeInMinutes?: number;
    minimumBatteryPercentageAtVisit?: number;
    maximumBatteryPercentageAtVisit?: number;
    minimumDesiredBatteryPercentageAtDestination?: number;
    maximumDesiredBatteryPercentageAtDestination?: number;
    initialBatteryRangeInMeters?: number;
    maxBatteryRangeInMeters?: number;
    currentType?: Array<ChargingPowerType> | null;
    maxBatteryPercentageOnCharge?: number;
    kwPerHunderedConsumption?: number;
    totalBatteryKW?: number;
}

