/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceRequestStatus } from './invoiceRequestStatus';
import { LeaseSharingInfo } from './leaseSharingInfo';


export interface UpdateInvoiceRequestCommand { 
    invoiceRequestId?: string | null;
    unitCost?: number | null;
    consumption?: number | null;
    totalEnergyCost?: number | null;
    totalSalesAmountIncludingTax?: number | null;
    taxRate?: number | null;
    monthlyEndorsement?: number | null;
    startDate?: string | null;
    endDate?: string | null;
    leaseSharingInfo?: LeaseSharingInfo;
    leaseAmount?: number | null;
    stationProfit?: number | null;
    totalInvoiceRequestAmount?: number | null;
    currencyId?: string | null;
    status?: InvoiceRequestStatus;
    siteHostId?: string | null;
    chargePointId?: string | null;
    workspaceId?: string | null;
}
export namespace UpdateInvoiceRequestCommand {
}


