/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignVisibility } from './campaignVisibility';
import { CampaignStatus } from './campaignStatus';
import { ChargePointAccessibility } from './chargePointAccessibility';
import { CouponLimitType } from './couponLimitType';
import { StringActionTypeTuple } from './stringActionTypeTuple';
import { CampaignType } from './campaignType';


export interface UpdateCampaignCommand { 
    campaignId?: string | null;
    name?: string | null;
    description?: string | null;
    subTitle?: string | null;
    campaignUrl?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    visibility?: CampaignVisibility;
    campaignType?: CampaignType;
    chargePointAccessibility?: ChargePointAccessibility;
    campaignAmount?: number | null;
    minimumEligibleAmount?: number | null;
    status?: CampaignStatus;
    workspaceChanges?: Array<StringActionTypeTuple> | null;
    externalId?: string | null;
    couponLimitType?: CouponLimitType;
    couponsCount?: number | null;
}
export namespace UpdateCampaignCommand {
}


