/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { ContactInfo } from './contactInfo';
import { BillingInfo } from './billingInfo';


export interface UpdateDirectoryCommand { 
    id?: string | null;
    name?: string | null;
    description?: string | null;
    website?: string | null;
    email?: string | null;
    phone?: string | null;
    logo?: string | null;
    contactInfo?: ContactInfo;
    address?: Address;
    billingInfo?: BillingInfo;
    userId?: string | null;
    isActive?: boolean | null;
    brandName?: string | null;
}

