/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type VoltageLevel = 'Undefined' | 'VoltageLevel_120V_1Phase' | 'VoltageLevel_208V_3Phase' | 'VoltageLevel_240V_1Phase' | 'VoltageLevel_240V_3Phase' | 'VoltageLevel_480V_3Phase' | 'Other';

export const VoltageLevel = {
    Undefined: 'Undefined' as VoltageLevel,
    VoltageLevel_120V_1Phase: 'VoltageLevel_120V_1Phase' as VoltageLevel,
    VoltageLevel_208V_3Phase: 'VoltageLevel_208V_3Phase' as VoltageLevel,
    VoltageLevel_240V_1Phase: 'VoltageLevel_240V_1Phase' as VoltageLevel,
    VoltageLevel_240V_3Phase: 'VoltageLevel_240V_3Phase' as VoltageLevel,
    VoltageLevel_480V_3Phase: 'VoltageLevel_480V_3Phase' as VoltageLevel,
    Other: 'Other' as VoltageLevel
};

