/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WorkspaceType = 'Undefined' | 'Home' | 'Work' | 'ChargingOperator' | 'ResidentialSite' | 'Other';

export const WorkspaceType = {
    Undefined: 'Undefined' as WorkspaceType,
    Home: 'Home' as WorkspaceType,
    Work: 'Work' as WorkspaceType,
    ChargingOperator: 'ChargingOperator' as WorkspaceType,
    ResidentialSite: 'ResidentialSite' as WorkspaceType,
    Other: 'Other' as WorkspaceType
};

