/**
 * CPMS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Amenity } from './amenity';
import { DomainEvent } from './domainEvent';
import { ChargePoint } from './chargePoint';
import { Tariff } from './tariff';
import { Invitation } from './invitation';
import { LeaseSharingInfo } from './leaseSharingInfo';
import { WorkingHour } from './workingHour';
import { BillingInfo } from './billingInfo';
import { WorkspaceCampaign } from './workspaceCampaign';
import { Reservation } from './reservation';
import { BankAccountInfo } from './bankAccountInfo';
import { WorkspaceType } from './workspaceType';
import { ContactInfo } from './contactInfo';
import { Directory } from './directory';


export interface Workspace { 
    readonly id?: string | null;
    created?: string;
    createdBy?: string | null;
    lastModified?: string | null;
    lastModifiedBy?: string | null;
    name?: string | null;
    description?: string | null;
    workspaceType?: WorkspaceType;
    contactInfo?: ContactInfo;
    bankAccountInfo?: BankAccountInfo;
    extraNote?: string | null;
    userId?: string | null;
    readonly domainEvents?: Array<DomainEvent> | null;
    leaseSharingInfo?: LeaseSharingInfo;
    isArchived?: boolean;
    archiveDate?: string | null;
    archivedBy?: string | null;
    imageUrl?: string | null;
    directoryId?: string | null;
    directory?: Directory;
    chargePoints?: Array<ChargePoint> | null;
    reservations?: Array<Reservation> | null;
    invitations?: Array<Invitation> | null;
    tariffs?: Array<Tariff> | null;
    eligibleCampaigns?: Array<WorkspaceCampaign> | null;
    billingInfo?: BillingInfo;
    readonly readableId?: string | null;
    isReservationsEnabled?: boolean | null;
    amenities?: Array<Amenity> | null;
    workingHours?: Array<WorkingHour> | null;
}
export namespace Workspace {
}


