export const Keys = {
  USER_TOKEN: 'USER_KEY',
  AUTHENTICATED_USER_DATA: 'AUTHENTICATED_USER_DATA',
  USER_DATA: 'USER_DATA',
  USER_ROLES_DATA: 'USER_ROLES_DATA',
  USER_POLICIES_DATA: 'USER_POLICIES_DATA',
  LANGUAGE: 'LANGUAGE',
  COUNTRIES: 'COUNTRIES',
  CURRENCIES: 'CURRENCIES',
  ROLES: 'ROLES',
  IsAutoTourStarted: 'isAutoTourStarted'
};

export const Patterns = {
  EMAIL_PATTERNS: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$'
};
